### ISSUE TITLE
No sounds, AI doesn't speak

### ISSUE THREAD

**Issue by jaghertv** [Clad3815/Twitch-Streamer-GPT#14]
Hello, thank you to create this Clad !

I actually have problem during installation.

So many error like : 

npm ERR! code 1
npm ERR! path C:\Users\IA\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@21.0.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.0 found at "C:\Users\IA\AppData\Local\Programs\Python\Python312\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\ProgramFiles\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2015 (C:\ProgramFiles\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:67:12
npm ERR! gyp ERR! stack     at failPowershell (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:156:7)
npm ERR! gyp ERR! stack     at VisualStudioFinder.parseData (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:170:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:143:14
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:414:7)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\IA\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker
npm ERR! gyp ERR! node -v v21.0.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\IA\AppData\Local\npm-cache\_logs\2023-10-18T11_09_54_964Z-debug-0.log

Can you help me please ? 

Best regards

**Comment by Clad3815** [comment]
Re install Nodejs and don't forget to tick the box "Automatically install..." Le 18 oct. 2023 13:13, jaghertv ***@***.***> a écrit :
Hello, thank you to create this Clad !
I actually have problem during installation.
So many error like :
npm ERR! code 1
npm ERR! path C:\Users\IA\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using ***@***.***
npm ERR! gyp info using ***@***.*** | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.0 found at "C:\Users\IA\AppData\Local\Programs\Python\Python312\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS not looking for VS2015 as it is only supported up to Node.js 18
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\ProgramFiles\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2015 (C:\ProgramFiles\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:364:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:67:12
npm ERR! gyp ERR! stack     at failPowershell (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:156:7)
npm ERR! gyp ERR! stack     at VisualStudioFinder.parseData (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:170:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:143:14
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:414:7)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\IA\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker
npm ERR! gyp ERR! node -v v21.0.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok
npm ERR! A complete log of this run can be found in: C:\Users\IA\AppData\Local\npm-cache_logs\2023-10-18T11_09_54_964Z-debug-0.log
Can you help me please ?
Best regards

**Comment by jaghertv** [comment]
I did it, but it still doesn't work.

I uninstalled NodeJS and reinstalled with the checkbox and during the installation I got this message. Is it a problem ? Is it important ?


python312 v3.12.0 [Approved]
python312 package files upgrade completed. Performing other installation steps.
Installing 64-bit python312...
WARNING: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python312_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error.
ERROR: Running ["C:\ProgramData\chocolatey\lib\python312\tools\python-3.12.0-amd64.exe" /quiet InstallAllUsers=1 PrependPath=1 TargetDir="C:\Python312" ] was not successful. Exit code was '1603'. Exit code indicates the following: Generic MSI Error. This is a local environment error, not an issue with a package or the MSI itself - it could mean a pending reboot is necessary prior to install or something else (like the same version is already installed). Please see MSI log if available. If not, try again adding '--install-arguments="'/l*v c:\python312_msi_install.log'"'. Then search the MSI Log for "Return Value 3" and look above that for the error..
The upgrade of python312 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\python312\tools\chocolateyInstall.ps1'.
 See log for details.
Progress: Downloading python3 3.12.0... 100%

python3 v3.12.0 [Approved]
python3 package files upgrade completed. Performing other installation steps.
 The upgrade of python3 was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\python3'
Progress: Downloading python 3.12.0... 100%

python v3.12.0 [Approved]
python package files upgrade completed. Performing other installation steps.
 The upgrade of python was successful.
  Software installed to 'C:\ProgramData\chocolatey\lib\python'
visualstudio2019-workload-vctools is not installed. Installing...
[NuGet] One or more unresolved package dependency constraints detected in the Chocolatey lib folder. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'python 3.12.0 constraint: python3 (= 3.12.0)'
Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.0.23026 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.0.0 constraint: kb2919355 (>= 1.0.20160915)'.

Chocolatey upgraded 12/14 packages. 2 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Upgraded:
 - chocolatey-compatibility.extension v1.0.0
 - chocolatey-core.extension v1.4.0
 - chocolatey-windowsupdate.extension v1.0.5
 - KB2919355 v1.0.20160915
 - KB2919442 v1.0.20160915
 - KB2999226 v1.0.20181019
 - KB3033929 v1.0.5
 - KB3035131 v1.0.3
 - python v3.12.0
 - python3 v3.12.0
 - vcredist140 v14.36.32532
 - vcredist2015 v14.0.24215.20170201

Failures
 - python312 (exited 1603) - Error while running 'C:\ProgramData\chocolatey\lib\python312\tools\chocolateyInstall.ps1'.
 See log for details.
 - visualstudio2019-workload-vctools - Unable to resolve dependency 'kb2919355': Unable to find a version of 'kb2919355' that is compatible with 'dotnetfx 4.7.2 constraint: kb2919355 (>= 1.0.20160915)', 'KB2999226 1.0.20161023 constraint: kb2919355 (>= 1.0.20160915)', 'vcredist140 14.0.23026 constraint: kb2919355 (>= 1.0.20160915)', 'visualstudio2019buildtools 16.0.0 constraint: kb2919355 (>= 1.0.20160915)'.

**Comment by jaghertv** [comment]
I don't know what is "code 1" but i think it's the problem no ?

**Comment by jaghertv** [comment]
Installation is now ok !

But the problem is still there.

Now, when I install node_vad, i have this message : 

Calibrating...
Calibration completed. SILENCE_THRESHOLD set to 3.686953125
Start listening
Wake word detected, start recording !
Playing from C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\wake_word_answer: 2.mp3
Audio player exited with code 1
Error details: C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\bindings\bindings.js:137
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\Debug\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\Release\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\out\Debug\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\Debug\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\out\Release\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\Release\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\default\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\compiled\21.0.0\win32\x64\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\release\install-root\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\debug\install-root\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\default\install-root\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\lib\binding\node-v120-win32-x64\binding.node
    at bindings (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\bindings\bindings.js:128:9)
    at Object.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\index.js:9:36)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1201:32)
    at Module._load (node:internal/modules/cjs/loader:1017:12)
    at Module.require (node:internal/modules/cjs/loader:1229:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\audioPlayer.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1369:14) {
  tries: [
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\Debug\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\Release\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\out\\Debug\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\Debug\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\out\\Release\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\Release\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\default\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\compiled\\21.0.0\\win32\\x64\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\release\\install-root\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\debug\\install-root\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\default\\install-root\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\lib\\binding\\node-v120-win32-x64\\binding.node'
  ]
}

Node.js v21.0.0

An unhandled rejection occurred!
Reason: Error: Audio player exited with code 1. Details: C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\bindings\bindings.js:137
  throw err;
  ^

Error: Could not locate the bindings file. Tried:
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\Debug\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\Release\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\out\Debug\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\Debug\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\out\Release\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\Release\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\default\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\compiled\21.0.0\win32\x64\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\release\install-root\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\debug\install-root\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\default\install-root\binding.node
 → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\lib\binding\node-v120-win32-x64\binding.node
    at bindings (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\bindings\bindings.js:128:9)
    at Object.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\index.js:9:36)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1201:32)
    at Module._load (node:internal/modules/cjs/loader:1017:12)
    at Module.require (node:internal/modules/cjs/loader:1229:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\audioPlayer.js:2:17)
    at Module._compile (node:internal/modules/cjs/loader:1369:14) {
  tries: [
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\Debug\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\Release\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\out\\Debug\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\Debug\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\out\\Release\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\Release\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\default\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\compiled\\21.0.0\\win32\\x64\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\release\\install-root\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\debug\\install-root\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\default\\install-root\\binding.node',
    'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\lib\\binding\\node-v120-win32-x64\\binding.node'
  ]
}

Node.js v21.0.0

    at ChildProcess.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\modules\voiceHandler.js:178:24)
    at ChildProcess.emit (node:events:515:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:515:28)
    at Pipe.<anonymous> (node:net:337:12)
Promise: Promise {
  <rejected> Error: Audio player exited with code 1. Details: C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\bindings\bindings.js:137
    throw err;
    ^

  Error: Could not locate the bindings file. Tried:
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\Debug\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\Release\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\out\Debug\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\Debug\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\out\Release\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\Release\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\build\default\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\compiled\21.0.0\win32\x64\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\release\install-root\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\debug\install-root\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\addon-build\default\install-root\binding.node
   → C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\lib\binding\node-v120-win32-x64\binding.node
      at bindings (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\bindings\bindings.js:128:9)
      at Object.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\node_modules\speaker\index.js:9:36)
      at Module._compile (node:internal/modules/cjs/loader:1369:14)
      at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
      at Module.load (node:internal/modules/cjs/loader:1201:32)
      at Module._load (node:internal/modules/cjs/loader:1017:12)
      at Module.require (node:internal/modules/cjs/loader:1229:19)
      at require (node:internal/modules/helpers:177:18)
      at Object.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\audioPlayer.js:2:17)
      at Module._compile (node:internal/modules/cjs/loader:1369:14) {
    tries: [
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\Debug\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\Release\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\out\\Debug\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\Debug\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\out\\Release\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\Release\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\build\\default\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\compiled\\21.0.0\\win32\\x64\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\release\\install-root\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\debug\\install-root\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\addon-build\\default\\install-root\\binding.node',
      'C:\\Users\\Mickael\\Documents\\GitHub\\Twitch-Streamer-GPT\\node_modules\\speaker\\lib\\binding\\node-v120-win32-x64\\binding.node'
    ]
  }

  Node.js v21.0.0

      at ChildProcess.<anonymous> (C:\Users\Mickael\Documents\GitHub\Twitch-Streamer-GPT\modules\voiceHandler.js:178:24)
      at ChildProcess.emit (node:events:515:28)
      at maybeClose (node:internal/child_process:1105:16)
      at Socket.<anonymous> (node:internal/child_process:457:11)
      at Socket.emit (node:events:515:28)
      at Pipe.<anonymous> (node:net:337:12)

**Comment by Clad3815** [comment]
Try tor  restart your computer and try again Le 18 oct. 2023 13:55, jaghertv ***@***.***> a écrit :
I don't know what is "code 1" but i think it's the problem no ?

**Comment by jaghertv** [comment]
I restart my computer and the problem is still there :/

**Comment by jaghertv** [comment]
Hello Clad3815, i still have a problem on this :(
can you help me ?

![image](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/148334282/27a9e287-b4de-4522-b484-0020ef8a9d48)

![image](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/148334282/1c5418c2-9043-4a0a-8313-69ded255b90f)

**Comment by jaghertv** [comment]
Hello Clad3815, i still have a problem on this :(
can you help me ?
I restart my computer.

I have no sound, I can't hear the AI, I can see the question and the written answer in the VoiceRecorder and on the TwitchBot, but I don't have an answer. Even when I ask the question to the AI ​​it is supposed to answer me something before I ask the question and I don't hear it (the question in the "wait_mp3" file

![image](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/148334282/27a9e287-b4de-4522-b484-0020ef8a9d48)

![image](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/148334282/1c5418c2-9043-4a0a-8313-69ded255b90f)
