### ISSUE TITLE
Message d'erreur à linstallation

### ISSUE THREAD

**Issue by EatSomePotatoes** [Clad3815/Twitch-Streamer-GPT#17]
Salut !

J'ai cherché un peu mais je ne trouve rien. J'ai ce message durant l'instal.bat.
(j'ai remplacé mon nom d'utilisateur par *monpseudo* )

Je déséspère ! :'( Pourtant j'aimerais trop que ça marche !!

npm ERR! code 1
npm ERR! path C:\Users\*monpseudo*\Twitch-Streamer-GPT-Zangdar\node_modules\speaker
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@21.1.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.12.0 found at "C:\Python312\python.exe"
npm ERR! gyp info find VS using VS2022 (17.7.34221.43) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Python312\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\*monpseudo*\\Twitch-Streamer-GPT-Zangdar\\node_modules\\speaker\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\*monpseudo*\\AppData\\Local\\node-gyp\\Cache\\21.1.0\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\*monpseudo*\\AppData\\Local\\node-gyp\\Cache\\21.1.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\*monpseudo*\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\21.1.0\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\*monpseudo*\\Twitch-Streamer-GPT-Zangdar\\node_modules\\speaker',npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'C:\\Users\\*monpseudo*\\Twitch-Streamer-GPT-Zangdar\\node_modules\\speaker\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! Could not find platform independent libraries <prefix>
npm ERR! Traceback (most recent call last):
npm ERR!   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 42, in <module>
npm ERR!     import gyp  # noqa: E402
npm ERR!     ^^^^^^^^^^
npm ERR!   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 9, in <module>
npm ERR!     import gyp.input
npm ERR!   File "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 19, in <module>
npm ERR!     from distutils.version import StrictVersion
npm ERR! ModuleNotFoundError: No module named 'distutils'
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:325:16)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:515:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19045
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\*monpseudo*\Twitch-Streamer-GPT-Zangdar\node_modules\speaker
npm ERR! gyp ERR! node -v v21.1.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\*monpseudo*\AppData\Local\npm-cache\_logs\2023-11-14T18_05_27_238Z-debug-0.log

C:\Users\*monpseudo*\Twitch-Streamer-GPT-Zangdar>

**Comment by EatSomePotatoes** [comment]
J'ai réinstallé python et js.node 30.000 fois mais rien à faire non plus. 
bref :(

**Comment by geekphane** [comment]
Salut, j'ai eu la même chose, si tu ne l'as pas fait il faut installer "visual studio" et "visual studio tools". Oui je sais ce n'est pas précisé mais il le faut.

**Comment by EatSomePotatoes** [comment]
J'avoue ne pas trop comprendre quoi comment installer visual studio. Quand on lance l'instal il te demande ce que tu veux installer et il y a mille options. me semblait qu'il fallait installer le "développement desktop C++" seulement non ?

Ensuite si je cherche à installer Visual Studio ou Visual Studio Tools ça me ramène toujours au même lien de téléchargement :
https://visualstudio.microsoft.com/fr/downloads/
C'est vraiment 2 trucs différents ?

En tout cas merci beaucoup d'essayer de m'aider ! :)

**Comment by EatSomePotatoes** [comment]
J'ai installé tout ça un peu en vrac sans trop comprendre : 
![image](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/149960912/b98703fd-6102-4ccd-b430-44fb6f1b41d5)

Il faut le lancer après ? En faisant un compte et tout ? Je capte rien ^^'
