### ISSUE TITLE
Bug reveille

### ISSUE THREAD

**Issue by CoCo7412** [Clad3815/Twitch-Streamer-GPT#2]
Bonjour je viens te demander un petit peut d'aide vis a vis de l'IA car quand je le réveil il détecte bien, mais derrière aucune réponse j'ai l'impression qu'il bug,

Wake word detected, start recording !
Playing from C:\Users\coul_\OneDrive\Bureau\IA\wake_word_answer: 1.mp3
Audio player exited with code 1
Error details: C:\Users\coul_\OneDrive\Bureau\IA\audioPlayer.js:93
        throw error;
        ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:759:9)
    at createFFmpeg (C:\Users\coul_\OneDrive\Bureau\IA\audioPlayer.js:80:18)
    at Object.<anonymous> (C:\Users\coul_\OneDrive\Bureau\IA\audioPlayer.js:132:16)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Node.js v20.5.1

C:\Users\coul_\OneDrive\Bureau\IA\modules\voiceHandler.js:178
                reject(new Error(`Audio player exited with code ${code}. Details: ${errorOutput}`));
                       ^

Error: Audio player exited with code 1. Details: C:\Users\coul_\OneDrive\Bureau\IA\audioPlayer.js:93
        throw error;
        ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:759:9)
    at createFFmpeg (C:\Users\coul_\OneDrive\Bureau\IA\audioPlayer.js:80:18)
    at Object.<anonymous> (C:\Users\coul_\OneDrive\Bureau\IA\audioPlayer.js:132:16)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Node.js v20.5.1

    at ChildProcess.<anonymous> (C:\Users\coul_\OneDrive\Bureau\IA\modules\voiceHandler.js:178:24)
    at ChildProcess.emit (node:events:514:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:514:28)
    at Pipe.<anonymous> (node:net:337:12)

Node.js v20.5.1

C:\Users\coul_\OneDrive\Bureau\IA>

**Comment by Clad3815** [comment]
C'est parce qu'il te manque "ffmpeg", tu peux essayer de faire:

```
npm remove ffmpeg-static
npm install ffmpeg-static
```

Si tu as encore le problème, active le "debug" dans le .env et envoie ici le fichier debug.log qui sera créé quand tu lance le bot
