### ISSUE TITLE
Problème lors du lancement

### ISSUE THREAD

**Issue by Antoinehpl** [Clad3815/Twitch-Streamer-GPT#21]
Bonjour voici l'erreur lors du lancement de startall.bat

"No history file found
[ERROR] keyword file belongs to a different version of the library. keyword file is `3.0.0` while the library is `2.2.0`.
[ERROR] loading keyword file at `C:\Users\herph\Desktop\Twitch-Streamer-GPT-main\wake_word\dit-moi-thomas_fr.ppn` failed with `INVALID_ARGUMENT`
Error loading wake word: Error: Porcupine failed to initialize
(node:61012) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Failed to initialize: TypeError: Cannot read properties of undefined (reading 'frameLength')"

Malgré le fait que j'ai téléchargé la v3 juste ici "https://github.com/Picovoice/porcupine/tree/master/lib/common"

Mais également sur l'autre .bat ceci

"Bot started and listening to channel 
(node:88768) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Twitch bot listening at http://localhost:3048
Using OpenAI model gpt-3.5-turbo.
node:internal/process/promises:289
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[InvalidTokenError: Invalid token supplied] {
  [cause]: [HttpStatusCodeError: Encountered HTTP status code 401: Unauthorized

  URL: validate
  Method: GET
  Body:
  {
    "status": 401,
    "message": "missing authorization token"
  }] {
    _statusCode: 401,
    _url: 'validate',
    _method: 'GET',
    _body: '{\n  "status": 401,\n  "message": "missing authorization token"\n}'
  }
}

Node.js v21.4.0 "

**Comment by Clad3815** [comment]
Essaie de mettre à jour Porcupine de la même manière que j'ai expliqué ici https://github.com/Clad3815/Twitch-Streamer-GPT/issues/19

**Comment by Antoinehpl** [comment]
Bonjour merci pour votre réponse mais aprés avoir fait ce que vous avez dit dans l'issue #19 cela ne fonctionne toujours pas 
![image_2023-12-17_204417959](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/91527724/66be8126-84b0-430c-b1c2-b8dea05ce6b2)
![image_2023-12-17_204432331](https://github.com/Clad3815/Twitch-Streamer-GPT/assets/91527724/b20cd88e-e91f-44d6-9f35-3838691094d0)

**Comment by MisterCoffeeYT** [comment]
Exactement le même problème de mon côté.
Malgré la solution apporté cela ne marche pas non plus pour moi, d'autres solutions ont-été trouvé ?
Merci d'avance !

**Comment by Clad3815** [comment]
J'ai fais une mise à jour du repo, essayez de re télécharger et faire le tuto normalement il ne devrait plus y avoir de problème

**Comment by Antoinehpl** [comment]
Bonjour merci pour ta réponse et la mise à jour, alors cela fonctionne mais lors de l'attente de la réponse après la question cela apparait "Error during transcription: Error: Connection error.

C:\Users\herph\Desktop\Twitch-Streamer-GPT-main\node_modules\axios\dist\node\axios.cjs:837
  AxiosError.call(axiosError, error.message, code, config, request, response);
             ^
AxiosError [AggregateError]
    at AxiosError.from (C:\Users\herph\Desktop\Twitch-Streamer-GPT-main\node_modules\axios\dist\node\axios.cjs:837:14)
    at RedirectableRequest.handleRequestError (C:\Users\herph\Desktop\Twitch-Streamer-GPT-main\node_modules\axios\dist\node\axios.cjs:3083:25)
    at RedirectableRequest.emit (node:events:519:28)
    at eventHandlers.<computed> (C:\Users\herph\Desktop\Twitch-Streamer-GPT-main\node_modules\follow-redirects\index.js:14:24)
    at ClientRequest.emit (node:events:519:28)
    at Socket.socketErrorListener (node:_http_client:495:9)
    at Socket.emit (node:events:519:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ECONNREFUSED',
  errors: [
    Error: connect ECONNREFUSED ::1:3048
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 3048
    },
    Error: connect ECONNREFUSED 127.0.0.1:3048
        at createConnectionError (node:net:1634:14)
        at afterConnectMultiple (node:net:1664:40) {
      errno: -4078,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 3048
    }
  ],
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: {
      FormData: [Function: FormData] {
        LINE_BREAK: '\r\n',
        DEFAULT_CONTENT_TYPE: 'application/octet-stream'
      },
      Blob: [class Blob]
    },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.6.2',
      'Content-Length': '2',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http://localhost:3048/transcription',
    data: '{}'
  },
  request: <ref *1> Writable {
    _events: {
      close: undefined,
      error: [Function: handleRequestError],
      prefinish: undefined,
      finish: undefined,
      drain: undefined,
      response: [Function: handleResponse],
      socket: [Function: handleRequestSocket]
    },
    _writableState: WritableState {
      highWaterMark: 16384,
      length: 0,
      corked: 0,
      onwrite: [Function: bound onwrite],
      writelen: 0,
      bufferedIndex: 0,
      pendingcb: 0,
      [Symbol(kState)]: 17580812,
      [Symbol(kBufferedValue)]: null
    },
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/transcription',
      method: 'POST',
      headers: [Object: null prototype] {
        Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json',
        'User-Agent': 'axios/1.6.2',
        'Content-Length': '2',
        'Accept-Encoding': 'gzip, compress, deflate, br'
      },
      agents: { http: undefined, https: undefined },
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: { proxy: [Function: beforeRedirect] },
      hostname: 'localhost',
      port: '3048',
      agent: undefined,
      nativeProtocols: {
        'http:': {
          _connectionListener: [Function: connectionListener],
          METHODS: [
            'ACL',         'BIND',       'CHECKOUT',
            'CONNECT',     'COPY',       'DELETE',
            'GET',         'HEAD',       'LINK',
            'LOCK',        'M-SEARCH',   'MERGE',
            'MKACTIVITY',  'MKCALENDAR', 'MKCOL',
            'MOVE',        'NOTIFY',     'OPTIONS',
            'PATCH',       'POST',       'PROPFIND',
            'PROPPATCH',   'PURGE',      'PUT',
            'REBIND',      'REPORT',     'SEARCH',
            'SOURCE',      'SUBSCRIBE',  'TRACE',
            'UNBIND',      'UNLINK',     'UNLOCK',
            'UNSUBSCRIBE'
          ],
          STATUS_CODES: {
            '100': 'Continue',
            '101': 'Switching Protocols',
            '102': 'Processing',
            '103': 'Early Hints',
            '200': 'OK',
            '201': 'Created',
            '202': 'Accepted',
            '203': 'Non-Authoritative Information',
            '204': 'No Content',
            '205': 'Reset Content',
            '206': 'Partial Content',
            '207': 'Multi-Status',
            '208': 'Already Reported',
            '226': 'IM Used',
            '300': 'Multiple Choices',
            '301': 'Moved Permanently',
            '302': 'Found',
            '303': 'See Other',
            '304': 'Not Modified',
            '305': 'Use Proxy',
            '307': 'Temporary Redirect',
            '308': 'Permanent Redirect',
            '400': 'Bad Request',
            '401': 'Unauthorized',
            '402': 'Payment Required',
            '403': 'Forbidden',
            '404': 'Not Found',
            '405': 'Method Not Allowed',
            '406': 'Not Acceptable',
            '407': 'Proxy Authentication Required',
            '408': 'Request Timeout',
            '409': 'Conflict',
            '410': 'Gone',
            '411': 'Length Required',
            '412': 'Precondition Failed',
            '413': 'Payload Too Large',
            '414': 'URI Too Long',
            '415': 'Unsupported Media Type',
            '416': 'Range Not Satisfiable',
            '417': 'Expectation Failed',
            '418': "I'm a Teapot",
            '421': 'Misdirected Request',
            '422': 'Unprocessable Entity',
            '423': 'Locked',
            '424': 'Failed Dependency',
            '425': 'Too Early',
            '426': 'Upgrade Required',
            '428': 'Precondition Required',
            '429': 'Too Many Requests',
            '431': 'Request Header Fields Too Large',
            '451': 'Unavailable For Legal Reasons',
            '500': 'Internal Server Error',
            '501': 'Not Implemented',
            '502': 'Bad Gateway',
            '503': 'Service Unavailable',
            '504': 'Gateway Timeout',
            '505': 'HTTP Version Not Supported',
            '506': 'Variant Also Negotiates',
            '507': 'Insufficient Storage',
            '508': 'Loop Detected',
            '509': 'Bandwidth Limit Exceeded',
            '510': 'Not Extended',
            '511': 'Network Authentication Required'
          },
          Agent: [Function: Agent] { defaultMaxSockets: Infinity },
          ClientRequest: [Function: ClientRequest],
          IncomingMessage: [Function: IncomingMessage],
          OutgoingMessage: [Function: OutgoingMessage],
          Server: [Function: Server],
          ServerResponse: [Function: ServerResponse],
          createServer: [Function: createServer],
          validateHeaderName: [Function: wrappedFn] {
            withoutStackTrace: [Function (anonymous)]
          },
          validateHeaderValue: [Function: wrappedFn] {
            withoutStackTrace: [Function (anonymous)]
          },
          get: [Function: get],
          request: [Function: request],
          setMaxIdleHTTPParsers: [Function: setMaxIdleHTTPParsers],
          maxHeaderSize: [Getter],
          globalAgent: [Getter/Setter]
        },
        'https:': {
          Agent: [Function: Agent],
          globalAgent: Agent {
            _events: [Object: null prototype],
            _eventsCount: 2,
            _maxListeners: undefined,
            defaultPort: 443,
            protocol: 'https:',
            options: [Object: null prototype],
            requests: [Object: null prototype] {},
            sockets: [Object: null prototype] {},
            freeSockets: [Object: null prototype] {},
            keepAliveMsecs: 1000,
            keepAlive: true,
            maxSockets: Infinity,
            maxFreeSockets: 256,
            scheduling: 'lifo',
            maxTotalSockets: Infinity,
            totalSocketCount: 0,
            maxCachedSessions: 100,
            _sessionCache: [Object],
            [Symbol(shapeMode)]: false,
            [Symbol(kCapture)]: false
          },
          Server: [Function: Server],
          createServer: [Function: createServer],
          get: [Function: get],
          request: [Function: request]
        }
      },
      pathname: '/transcription'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 2,
    _requestBodyBuffers: [
      {
        data: Buffer(2) [Uint8Array] [ 123, 125 ],
        encoding: undefined
      }
    ],
    _eventsCount: 3,
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: <ref *2> ClientRequest {
      _events: [Object: null prototype] {
        response: [Function: bound onceWrapper] {
          listener: [Function (anonymous)]
        },
        abort: [Function (anonymous)],
        aborted: [Function (anonymous)],
        connect: [Function (anonymous)],
        error: [Function (anonymous)],
        socket: [Function (anonymous)],
        timeout: [Function (anonymous)]
      },
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: false,
      chunkedEncoding: false,
      shouldKeepAlive: true,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '2',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      _header: 'POST /transcription HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.6.2\r\n' +
        'Content-Length: 2\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: localhost:3048\r\n' +
        'Connection: keep-alive\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: Agent {
        _events: [Object: null prototype] {
          free: [Function (anonymous)],
          newListener: [Function: maybeEnableKeylog]
        },
        _eventsCount: 2,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object: null prototype] {
          keepAlive: true,
          scheduling: 'lifo',
          timeout: 5000,
          noDelay: true,
          path: null
        },
        requests: [Object: null prototype] {},
        sockets: [Object: null prototype] { 'localhost:3048:': [ [Socket] ] },
        freeSockets: [Object: null prototype] {},
        keepAliveMsecs: 1000,
        keepAlive: true,
        maxSockets: Infinity,
        maxFreeSockets: 256,
        scheduling: 'lifo',
        maxTotalSockets: Infinity,
        totalSocketCount: 1,
        [Symbol(shapeMode)]: false,
        [Symbol(kCapture)]: false
      },
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/transcription',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'localhost',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(shapeMode)]: false,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kChunkedBuffer)]: [],
      [Symbol(kChunkedLength)]: 0,
      [Symbol(kSocket)]: Socket {
        connecting: false,
        _hadError: true,
        _parent: null,
        _host: 'localhost',
        _closeAfterHandlingError: false,
        _events: {
          close: [
            [Function: onClose],
            [Function: socketCloseListener],
            [Function]
          ],
          error: [Function: socketErrorListener],
          prefinish: undefined,
          finish: undefined,
          drain: [Function: ondrain],
          data: undefined,
          end: [Function: onReadableStreamEnd],
          readable: undefined,
          connect: [ [Function], [Function], [Function] ],
          free: [Function: onFree],
          timeout: [ [Function: onTimeout], [Function] ],
          agentRemove: [Function: onRemove]
        },
        _readableState: ReadableState {
          highWaterMark: 16384,
          buffer: [],
          bufferIndex: 0,
          length: 0,
          pipes: [],
          awaitDrainWriters: null,
          [Symbol(kState)]: 59777526,
          [Symbol(kErroredValue)]: AggregateError [ECONNREFUSED]:
              at internalConnectMultiple (node:net:1114:18)
              at afterConnectMultiple (node:net:1667:5) {
            code: 'ECONNREFUSED',
            [errors]: [Array]
          }
        },
        _writableState: WritableState {
          highWaterMark: 16384,
          length: 245,
          corked: 0,
          onwrite: [Function: bound onwrite],
          writelen: 245,
          bufferedIndex: 0,
          pendingcb: 1,
          [Symbol(kState)]: 118260214,
          [Symbol(kBufferedValue)]: null,
          [Symbol(kWriteCbValue)]: [Function (anonymous)],
          [Symbol(kErroredValue)]: AggregateError [ECONNREFUSED]:
              at internalConnectMultiple (node:net:1114:18)
              at afterConnectMultiple (node:net:1667:5) {
            code: 'ECONNREFUSED',
            [errors]: [Array]
          }
        },
        allowHalfOpen: false,
        _maxListeners: undefined,
        _eventsCount: 8,
        _sockname: null,
        _pendingData: [
          {
            chunk: 'POST /transcription HTTP/1.1\r\n' +
              'Accept: application/json, text/plain, */*\r\n' +
              'Content-Type: application/json\r\n' +
              'User-Agent: axios/1.6.2\r\n' +
              'Content-Length: 2\r\n' +
              'Accept-Encoding: gzip, compress, deflate, br\r\n' +
              'Host: localhost:3048\r\n' +
              'Connection: keep-alive\r\n' +
              '\r\n',
            encoding: 'latin1',
            callback: [Function: nop]
          },
          {
            chunk: [Buffer [Uint8Array]],
            encoding: 'buffer',
            callback: [Function (anonymous)]
          },
          allBuffers: false
        ],
        _pendingEncoding: '',
        server: null,
        _server: null,
        timeout: 5000,
        parser: null,
        _httpMessage: [Circular *2],
        autoSelectFamilyAttemptedAddresses: [ '::1:3048', '127.0.0.1:3048' ],
        [Symbol(async_id_symbol)]: 710,
        [Symbol(kHandle)]: null,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: Timeout {
          _idleTimeout: -1,
          _idlePrev: null,
          _idleNext: null,
          _idleStart: 49793,
          _onTimeout: null,
          _timerArgs: undefined,
          _repeat: null,
          _destroyed: true,
          [Symbol(refed)]: false,
          [Symbol(kHasPrimitive)]: false,
          [Symbol(asyncId)]: 701,
          [Symbol(triggerId)]: 0
        },
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(shapeMode)]: true,
        [Symbol(kCapture)]: false,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(kSetKeepAlive)]: true,
        [Symbol(kSetKeepAliveInitialDelay)]: 60,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0
      },
      [Symbol(kOutHeaders)]: [Object: null prototype] {
        accept: [ 'Accept', 'application/json, text/plain, */*' ],
        'content-type': [ 'Content-Type', 'application/json' ],
        'user-agent': [ 'User-Agent', 'axios/1.6.2' ],
        'content-length': [ 'Content-Length', '2' ],
        'accept-encoding': [ 'Accept-Encoding', 'gzip, compress, deflate, br' ],
        host: [ 'Host', 'localhost:3048' ]
      },
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://localhost:3048/transcription',
    [Symbol(shapeMode)]: true,
    [Symbol(kCapture)]: false
  },
  cause: AggregateError [ECONNREFUSED]:
      at internalConnectMultiple (node:net:1114:18)
      at afterConnectMultiple (node:net:1667:5) {
    code: 'ECONNREFUSED',
    [errors]: [
      Error: connect ECONNREFUSED ::1:3048
          at createConnectionError (node:net:1634:14)
          at afterConnectMultiple (node:net:1664:40) {
        errno: -4078,
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '::1',
        port: 3048
      },
      Error: connect ECONNREFUSED 127.0.0.1:3048
          at createConnectionError (node:net:1634:14)
          at afterConnectMultiple (node:net:1664:40) {
        errno: -4078,
        code: 'ECONNREFUSED',
        syscall: 'connect',
        address: '127.0.0.1',
        port: 3048
      }
    ]
  }
}

Node.js v21.4.0
"

**Comment by Clad3815** [comment]
Il faut que le bot twitch soit lancé aussi, le voiceRecorder envoie le texte au bot twitch qui lui gère la communication avec GPT etc ...
