### ISSUE TITLE
erreur à la captation du wake word

### ISSUE THREAD

**Issue by patograso** [Clad3815/Twitch-Streamer-GPT#24]
Wake word detected, start recording !
Playing from C:\Users\xxxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\wake_word_answer: 1.mp3
Audio player exited with code 1
Error details: C:\Users\xxxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\audioPlayer.js:93
        throw error;
        ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at createFFmpeg (C:\Users\xxxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\audioPlayer.js:80:18)
    at Object.<anonymous> (C:\Users\xxxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\audioPlayer.js:132:16)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Node.js v21.5.0

C:\Users\xxxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\modules\voiceHandler.js:178
                reject(new Error(`Audio player exited with code ${code}. Details: ${errorOutput}`));
                       ^

Error: Audio player exited with code 1. Details: C:\Users\xxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\audioPlayer.js:93
        throw error;
        ^

Error: spawn UNKNOWN
    at ChildProcess.spawn (node:internal/child_process:421:11)
    at spawn (node:child_process:761:9)
    at createFFmpeg (C:\Users\xxxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\audioPlayer.js:80:18)
    at Object.<anonymous> (C:\Users\xxxx\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\audioPlayer.js:132:16)
    at Module._compile (node:internal/modules/cjs/loader:1375:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1434:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:142:12)
    at node:internal/main/run_main_module:28:49 {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'spawn'
}

Node.js v21.5.0

    at ChildProcess.<anonymous> (C:\Users\patog\Desktop\Twitch-Streamer-GPT-main\Twitch-Streamer-GPT-main\modules\voiceHandler.js:178:24)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at Socket.<anonymous> (node:internal/child_process:457:11)
    at Socket.emit (node:events:519:28)
    at Pipe.<anonymous> (node:net:337:12)

Node.js v21.5.0

**Comment by patograso** [comment]
reinstall fixed
